#!/bin/sh

AOS_BIN=node_modules/.bin/aos
AOS_WALLET_FILE=../wallets/aos-wallet.json
SCHEDULER_LOCATION_PUBLISHER_WALLET_FILE=../wallets/scheduler-location-publisher-wallet.json

cd $(dirname $0)

for wallet in $AOS_WALLET_FILE $SCHEDULER_LOCATION_PUBLISHER_WALLET_FILE; do
  if [ ! -f "$wallet" ]; then
    echo "wallet does not exist: $(pwd)/$wallet"
    exit 1
  fi
done

if [ ! -f "$AOS_BIN" ]; then
  npm install
fi

# Graphql query to Arlocal to automatically discover the AOS module tx id
AOS_MODULE=$(
node --input-type=module <<EOF
const query = \`query {
  transactions (
    tags: [
      { name: "Data-Protocol", values: ["ao"] },
      { name: "Type", values: ["Module"] },
      { name: "Content-Type", values: ["application/wasm"] },
    ],
    sort: HEIGHT_DESC, first: 1
  ) {
    edges { node { id } }
  }
}\`
const body = JSON.stringify({ query })
const res = await fetch('http://localhost:4000/graphql', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body,
})
console.log((await res.json()).data.transactions.edges[0].node.id)
EOF
)

# The SCHEDULER env var should be set to the wallet address that published a tx with a 'Scheduler-Location' tag
SCHEDULER=$(
node --input-type=module <<EOF
  import { readFile } from 'node:fs/promises'
  import Arweave from 'arweave'
  const arweave = new Arweave({
    protocol: 'http',
    host: 'localhost',
    port: 4000,
  })
  const walletJson = await readFile('$SCHEDULER_LOCATION_PUBLISHER_WALLET_FILE', 'utf8')
  const wallet = JSON.parse(walletJson)
  const address = await arweave.wallets.getAddress(wallet)
  console.log(address)
EOF
)

ARWEAVE_GRAPHQL=http://localhost:4000/graphql
CU_URL=http://localhost:4004
GATEWAY_URL=http://localhost:4000
MU_URL=http://localhost:4002

echo "AOS_MODULE      = $AOS_MODULE"
echo "ARWEAVE_GRAPHQL = $ARWEAVE_GRAPHQL"
echo "CU_URL          = $CU_URL"
echo "GATEWAY_URL     = $GATEWAY_URL"
echo "MU_URL          = $MU_URL"
echo "SCHEDULER       = $SCHEDULER"
export AOS_MODULE
export ARWEAVE_GRAPHQL
export CU_URL
export GATEWAY_URL
export MU_URL
export SCHEDULER
$AOS_BIN --wallet "$AOS_WALLET_FILE" "$@"
